[project]
name = "stacks-counter"
description = "A simple counter smart contract for the Stacks blockchain"
authors = ["Abdulrazak malik <hexchange001@gmail.com>"]
telemetry = true
cache_dir = "./.clarinet"

[contracts.counter]
path = "contracts/counter.clar"
clarity_version = 2
epoch = 2.4

[repl]
costs_version = 2
parser_version = 2
