[network]
name = "mainnet"
node_rpc_address = "https://stacks-node-api.mainnet.stacks.co"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "YOUR_MAINNET_MNEMONIC_HERE"
# Replace with your actual mainnet mnemonic for deployment
# WARNING: Never commit real mainnet mnemonics to version control!
