[network]
name = "testnet"
node_rpc_address = "https://stacks-node-api.testnet.stacks.co"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "YOUR_TESTNET_MNEMONIC_HERE"
# Replace with your actual testnet mnemonic for deployment
